[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/klinik"
  to = "/.netlify/functions/klinik"
  status = 200
  force = true

[[redirects]]
  from = "/api/client-error"
  to = "/.netlify/functions/client-error"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
